version: '3.5'
networks:
  pynet:
    name: 'pynet'
    driver: bridge
services:
  round-robin1:
    container_name: round-robin1
    build: .
    expose:
      - 4500
    networks:
      - pynet
  round-robin2:
    container_name: round-robin2
    build: .
    expose:
      - 4500
    networks:
      - pynet
    depends_on:
      - round-robin1
  nginx:
    image: nginx:latest
    container_name: round-robin-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "4006:443"
    networks:
      - pynet
    depends_on:
      - round-robin2
