version: '3.5'
networks:
  node-nginx-net:
    name: 'node-nginx-net'
    driver: bridge
services:
  upstream-encryption:
    container_name: upstream-encryption
    build: .
    environment:
      NODE_ENV: development
    expose:
      - 4500
    networks:
      - node-nginx-net
  nginx:
    image: nginx:latest
    container_name: upstream-encryption-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - node-nginx-net
    depends_on:
      - upstream-encryption
