version: '3.5'
networks:
  node-nginx-net:
    name: 'node-nginx-net'
    driver: bridge
services:
  https-server:
    container_name: https-server
    build: .
    environment:
      NODE_ENV: development
    expose:
      - 4500
    networks:
      - node-nginx-net
  nginx:
    image: nginx:latest
    container_name: https-server-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      - node-nginx-net
    depends_on:
      - https-server
