version: '3.5'
networks:
  node-nginx-net:
    name: 'node-nginx-net'
    driver: bridge
services:
  allow-cors:
    container_name: allow-cors
    build: .
    environment:
      NODE_ENV: development
    expose:
      - 4500
    networks:
      - node-nginx-net
  nginx:
    image: nginx:latest
    container_name: allow-cors-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "4006:443"
    networks:
      - node-nginx-net
    depends_on:
      - allow-cors
