version: '3.5'
networks:
  pynet:
    name: 'pynet'
    driver: bridge
services:
  least-time1:
    container_name: least-time1
    build: .
    expose:
      - 4500
    networks:
      - pynet
  least-time2:
    container_name: least-time2
    build: .
    expose:
      - 4500
    networks:
      - pynet
    depends_on:
      - least-time1
  nginx:
    image: nginx:latest
    container_name: least-time-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
      - "4006:443"
    networks:
      - pynet
    depends_on:
      - least-time2
